use_frameworks!

target 'Home_Example' do
  pod 'Home', :path => '../'

  target 'Home_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
